on:
  push:
    branches:
      - main

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hennejg/github-tag-action@v4.3.1
        with:
          release_branches: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
