on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: gradle
      - run: ./gradlew build --no-daemon
        env:
          RELEASE_VERSION: abc
      - uses: actions/upload-artifact@v4
        with:
          path: plugin/*/build/libs/*.jar
      - if: github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          title: ${{ github.sha }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: plugin/*/build/libs/*.jar
