on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
      - if: github.ref == 'refs/heads/main'
        uses: mathieudutour/github-tag-action@v6.2
        id: create-tag
        with:
          default_bump: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew build
        env:
          RELEASE_VERSION: ${{ steps.create-tag.outputs.new_tag || steps.short-sha.outputs.sha }}
      - uses: actions/upload-artifact@v4
        with:
          path: plugin/*/build/libs/*.jar
      - if: steps.create-tag.outputs.new_tag
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          title: ${{ steps.create-tag.outputs.new_tag }}
          automatic_release_tag: ${{ steps.create-tag.outputs.new_tag }}
          prerelease: false
          files: plugin/*/build/libs/*.jar
          repo_token: ${{ secrets.GITHUB_TOKEN }}
