on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew build
      - uses: actions/upload-artifact@v4
        with:
          path: plugin/*/build/libs/*.jar
      - if: startsWith(github.ref, 'refs/tags/v')
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          prerelease: false
          files: plugin/*/build/libs/*.jar
          repo_token: ${{ secrets.GITHUB_TOKEN }}
