on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
      - if: github.ref == 'refs/heads/main'
        uses: hennejg/github-tag-action@v4.3.1
        id: create-tag
        with:
          release_branches: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: ARTIFACT_VERSION=abc ./gradlew build
      - uses: actions/upload-artifact@v4
        with:
          path: plugin/*/build/libs/*.jar
      - if: steps.create-tag.outputs.new_tag
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          title: ${{ steps.create-tag.outputs.new_tag }}
          automatic_release_tag: ${{ steps.create-tag.outputs.new_tag }}
          prerelease: false
          files: plugin/*/build/libs/*.jar
          repo_token: ${{ secrets.GITHUB_TOKEN }}
